// Input Matrix: [ [ 1, 2, 3 ] 
//                 [ 4, 5, 6 ] 
//                 [ 7, 8, 9 ] ]

// Output Matrix: [ [ 4, 1, 2 ] 
//                  [ 7, 5, 3 ] 
//                  [ 8, 9, 6 ] ]

// The output matrix is generated by rotating the elements of the input matrix in a clockwise direction. Note that every element is rotated only once. 

// This Algorithm handles only cases when (N = M)


import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

public class Demo {

    public static void rotateClockwise(int[][] arr) {
        int n = arr.length;
        int m = arr[0].length;
        if(n == 1 || m == 1) return;
        int loops = n/2;
        for(int i = 0; i < loops; ++i) {
            
            int x, y;
            x = y = i;
            int prev = arr[x][y];
            int temp;

            do {
                if(y != n-1) {
                    System.out.println(x+" "+y);
                    temp = arr[x][y+1];
                    arr[x][y+1] = prev;
                    prev = temp;
                    y++;
                }
                else {
                    System.out.println(x+" "+y);
                    temp = arr[x+1][y];
                    arr[x+1][y] = prev;
                    prev = temp;
                    x++;
                }
            } while(x != y);

            do {
                if(y != i) {
                    temp = arr[x][y-1];
                    arr[x][y-1] = prev;
                    prev = temp;
                    y--;
                }
                else {
                    temp = arr[x-1][y];
                    arr[x-1][y] = prev;
                    prev = temp;
                    x--;
                }
            } while(x != y);

            n--;
        }
    }
    
    public static void main(String[] args) throws IOException {
        File inputfile = new File("input.txt");
        Scanner input = new Scanner(inputfile);
        FileWriter output = new FileWriter("output.txt");

        int n = input.nextInt();
        int m = input.nextInt();

        int[][] arr = new int[n][m];

        for(int i = 0; i < n; i++) {
            for(int j = 0; j < m; j++)
                arr[i][j] = input.nextInt();
        }

        rotateClockwise(arr);
        
        for(int[] row : arr) {
            for(int elem : row)
                output.write(Integer.toString(elem) + " ");
            output.write("\n");
        }

        input.close();
        output.close();
        
    }
}
