// Input Matrix: [ [ 1, 2, 3 ] 
//                 [ 4, 5, 6 ] 
//                 [ 7, 8, 9 ] ]

// Output Matrix: [ [ 4, 1, 2 ] 
//                  [ 7, 5, 3 ] 
//                  [ 8, 9, 6 ] ]

// The output matrix is generated by rotating the elements of the input matrix in a clockwise direction. Note that every element is rotated only once. 

// This Algorithm handles (N != M) constraint

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

public class Demo2 {

    public static void rotateClockwise(int[][] arr) {
        int n = arr.length;
        int m = arr[0].length;
        if(n == 1 || m == 1) return;

        // int loops = n/2;
        int i = 0;
        while(n > 1 && m > 1) {
            
            int x, y;
            x = y = i;
            int prev = arr[x][y];
            int temp;

            do {
                if(y != m+i-1) {
                    // System.out.println(x+" "+y);
                    temp = arr[x][y+1];
                    arr[x][y+1] = prev;
                    prev = temp;
                    y++;
                }
                else {
                    // System.out.println(x+" "+y);
                    temp = arr[x+1][y];
                    arr[x+1][y] = prev;
                    prev = temp;
                    x++;
                }
            } while(x != n+i-1 || y != m+i-1);

            do {
                if(y != i) {
                    temp = arr[x][y-1];
                    arr[x][y-1] = prev;
                    prev = temp;
                    y--;
                }
                else {
                    temp = arr[x-1][y];
                    arr[x-1][y] = prev;
                    prev = temp;
                    x--;
                }
            } while(x != i || y != i);

            n -= 2;
            m -= 2;
            i++;
        }
    }
    
    public static void main(String[] args) throws IOException {
        File inputfile = new File("input.txt");
        Scanner input = new Scanner(inputfile);
        FileWriter output = new FileWriter("output.txt");

        int n = input.nextInt();
        int m = input.nextInt();

        int[][] arr = new int[n][m];

        for(int i = 0; i < n; i++) {
            for(int j = 0; j < m; j++)
                arr[i][j] = input.nextInt();
        }

        rotateClockwise(arr);
        
        for(int[] row : arr) {
            for(int elem : row)
                output.write(Integer.toString(elem) + " ");
            output.write("\n");
        }

        input.close();
        output.close();
        
    }
}
